# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-19 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
