# Generated by Django 2.0 on 2018-08-09 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20170319_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinate',
            old_name='address',
            new_name='Address',
        ),
        migrations.RemoveField(
            model_name='coordinate',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='coordinate',
            name='lng',
        ),
        migrations.AddField(
            model_name='coordinate',
            name='Creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinate',
            name='Latitude',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='Longitude',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='Unique_ID',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
